### ISSUE TITLE
Meson Metaissue

### ISSUE THREAD

**Issue by ntonnaett** [thestk/rtaudio#316]
Missing from meson build:

- [ ] visibility=hidden: shared_library('mylib', ... gnu_symbol_visibility: 'hidden')
- [ ] check version: RTAUDIO_VERSION=`sed -n 's/#define RTAUDIO_VERSION "\(.*\)"/\1/p' $srcdir/RtAudio.h`
- [ ] doxygen
- [ ] check if ossaudio dependency lookup works
- [ ] Auto wasapi and asio
- [ ] generate cmake files
- [ ] tests

**Comment by ntonnaett** [comment]
Closing because of #317
